/***********************************************************************/
/*                                                                     */
/*  FILE        :heap.c                                                */
/*  DATE        :Mon, Jan 02, 2017                                     */
/*  DESCRIPTION :define the size of heap.                              */
/*  CPU GROUP   :35C                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/************************************************************************
*
* Device     : R8C Family
*
* File Name  : heap.c
*
* Abstract   : allocate heap area.
*
* History    : 1.80  (2006-06-13)
*
* NOTE       : THIS IS A TYPICAL EXAMPLE.
*
*  Copyright (C) 2006 Renesas Electronics Corporatio.
*  and Renesas Solutions Corp.
*
************************************************************************/
#include "typedefine.h"
#include "cstartdef.h"

#if __HEAPSIZE__ != 0
#pragma SECTION	bss	heap

_UBYTE heap_area[__HEAPSIZE__];
#endif
