/***********************************************************************/
/*                                                                     */
/*  FILE        :resetprg.c                                            */
/*  DATE        :Mon, Jan 02, 2017                                     */
/*  DESCRIPTION :initialize for C language.                            */
/*  CPU GROUP   :35C                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/*********************************************************************
*
* Device     : R8C/35C Group
*
* File Name  : resetprg.c
*
* Abstract   : Initialize for C language.
*
* History    : 1.00  (2010-04-05)  [Hardware Manual Revision : 1.00]
*
* NOTE       : THIS IS A TYPICAL EXAMPLE.
*
* Copyright (C) 2010 Renesas Electronics Corporation.
* and Renesas Solutions Corp.
*
*********************************************************************/
#include "sfr_r835c.h"
#include "typedefine.h"
#include "resetprg.h"

DEF_SBREGISTER;
extern _UINT	_stack_top,_istack_top;
#pragma entry start
void start(void);
extern void initsct(void);
extern void _init(void);
void exit(void);
void main(void);
void _CALL_INIT(void);
void _CALL_END(void);

#pragma section program interrupt 

void start(void)
{
	_isp_	= &_istack_top; 	// set interrupt stack pointer
	prcr	= 0x02U;		// change protect mode register
	pm0	= 0x00U;		// set processor mode register
	prcr	= 0x00U;		// change protect mode register
	_flg_	= __F_value__;	// set flag register
#if __STACKSIZE__!=0
	_sp_	= &_stack_top; 	// set user stack pointer
#endif
	_sb_	= 0x400U;	// 400H fixation (Do not change)
	_intbh_ = 0x00U; 	// set variable vector's address
	_asm("	ldc	#(topof vector)&0FFFFh,INTBL");

	initsct();		// initlalize each sections

#if __HEAPSIZE__ != 0
	heap_init();		// initialize heap 
#endif
#if __STANDARD_IO__ != 0
	_init();			// initialize standard I/O
#endif
	_fb_ = 0U;		// initialize FB registe for debugger
	// _CALL_INIT();		// dynamic initialize non_local objects
	main();			// call main routine

	exit();		// call exit
}

void exit(void)
{
	// _CALL_END();			// for static storage object destruct
	while(1)
	{
		;		//infinite loop
	}
}


