/***********************************************************************/
/*                                                                     */
/*  FILE        :typedefine.h                                          */
/*  DATE        :Mon, Jan 02, 2017                                     */
/*  DESCRIPTION :define scalar types.                                  */
/*  CPU GROUP   :35C                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
/************************************************************************
*
* Device     : R8C Family
*
* File Name  : typrdefine.h
*
* Abstract   : typedef for startup.
*
* History    : 1.40  (2005-11-01)
*
* NOTE       : THIS IS A TYPICAL EXAMPLE.
*
* Copyright (C) 2005 Renesas Electronics Corporation.
* and Renesas Solutions Corp.
*
************************************************************************/
#ifndef __TYPEDEF__
typedef signed char _SBYTE;
typedef unsigned char _UBYTE;
typedef signed short _SWORD;
typedef unsigned short _UWORD;
typedef signed int _SINT;
typedef unsigned int _UINT;
typedef signed long _SDWORD;
typedef unsigned long _UDWORD;
typedef signed long long _SQDWORD;
typedef unsigned long long _UQDWORD;
#endif
#define __TYPEDEF__
