/***********************************************************************/
/*                                                                     */
/*  FILE        :work17_i2cjisaku.c                                    */
/*  DATE        :Mon, Jan 02, 2017                                     */
/*  DESCRIPTION :main program file.                                    */
/*  CPU GROUP   :35C                                                   */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.19).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/***********************************************************************/
#include "sfr_r835c.h"
#include "uart1.h"
#include "my_string.h"
#include "MPL115A2.h"


void main(void);
void hw_init(void);

void main(void)
{
	int nRtn,i;
	unsigned char abyData[10];
	unsigned short uwPadc;
	unsigned short uwTadc;
	char sTmp[10];
	hw_init();
	i2c_init();
	uart1_init();
	
	while(1) {


		nRtn = MPL115A2_startADC();
		if(nRtn == I2C_ERROR) {
			uart1_write("i2c communication failed\r\n");
			for(i=0;i<0xff; i++);
			continue;
		}
		
		for (i=0; i<0xfff; i++); //wait for approx. 5msec
		
		nRtn = MPL115A2_readrawdata(&uwPadc, &uwTadc);
		if(nRtn == I2C_ERROR) {
			uart1_write("i2c communication failed\r\n");
			for(i=0;i<0xff; i++);
			continue;
		}

		my_itoa(uwPadc, sTmp, 10);
		uart1_write(sTmp);
		uart1_write(" ");
		my_itoa(uwTadc, sTmp, 10);
		uart1_write(sTmp);
		uart1_write("\r\n");

		for (i=0; i<0x4fff; i++);
	}
}


void hw_init(void)
{
	_asm(" FCLR I");
	////クロックの設定////
	//プロテクションoff
	prc0 = 1;	
	//高速オンチップオシレータ発振
	fra00 = 1;
	//高速オンチップオシレータ選択
	fra01 = 1;
	//cm16, cm17を有効
	cm06 = 0;
	//CM1レジスタ、分周無し
	//システムクロックは40/2=20MHz
	cm16 = 0;
	cm17 = 0;
	//プロテクションon
	prc0 = 0;
	///////////////////////
	_asm(" FSET I");

	//ポートの設定
	pd3_1 = 1; // port3_1 output
	pd3_3 = 1;
	drr06 = 1; // p3_0 - p3_3 high power drive

}
